config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'signup', to: 'users#new', as: 'signup'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :destroy, :create]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :username, :email, :password_digest, :firstname, :lastname, :birthday
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_uniqueness_of :username, :email
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Welcome back to Health Planner"
      redirect_to root_path
    else
      flash.now[:warning] = "Invalid Username or Password"
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Health Planner"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    user_params = params.require(:user).permit(:username, :firstname, :lastname, :birthday, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user || User.find(session[:user_id]) if logged_in?
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h3> Welcome to the homepage </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthPlanner</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
  <!-- <a href="#"> Appointments </a> -->
  <%= link_to "Login", signin_path %>
  <%= link_to "Signup", signup_path %>
  <%= link_to "Signout", signout_path %>
</div>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h3> Sign Up here! </h3>

<%= form_for @user do |f| %>
  <div> Username: <%= f.text_field :username %></div>
  <div> Password: <%= f.password_field :password %> </div>
  <div> Password Confirmation: <%= f.password_field :password_confirmation %> </div>
  <div> First name: <%= f.text_field :firstname %> </div>
  <div> Last name: <%= f.text_field :lastname %> </div>
  <div> Email: <%= f.text_field :email %> </div>
  <div> Birthday: <%= f.date_field :birthday %> </div>
  <div> <%= f.submit %> </div>
<% end %>